export enum MongoDbConfigEnum {
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASS = 'DATABASE_PASS',
}

export enum EmailConfigEnum {
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_AUTH_USER = 'EMAIL_AUTH_USER',
  EMAIL_AUTH_PASS = 'EMAIL_AUTH_PASS',
}

export enum GitHubLoginConfigEnum {
  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
  GITHUB_CLIENT_URL = 'GITHUB_CLIENT_URL',
  GITHUB_USER_INFO_URL = 'GITHUB_USER_INFO_URL',
  GITHUB_CALLBACK_URL = 'GITHUB_CALLBACK_URL',
}
